### PR TITLE
Support for netcore / netstandard1.6

### LINKED ISSUE #1: .NET Core
referencing https://github.com/mausch/Fuchu/pull/51

There is still some work ahead, mainly with `Expecto.Tests`. NUnit has .NET Core as a platform target now. FsCheck seems to be pending support (https://github.com/fscheck/FsCheck/pull/293).

PerfUtil and MbUnit seem to be the main issues right now as none of them seem to be actively maintained anymore. @mausch mentioned possibly dropping support for MbUnit. The way I see it, the alternatives are either porting those libs to .NET Core and hoping that a PR can be accepted, forking them or dropping support for PerfUtil and MbUnit.

### PR DESCRIPTION
**Pull request by adamchester**
Fixes #1 by adding Support for netcore / `netstandard1.6`

In this PR, I have reworked the commit history from:
 * #137
 * https://github.com/haf/expecto/tree/adamchester-netcore
 * https://github.com/haf/expecto/tree/netcore

in order to allow merging into `master`.

See also:
 * #123
 * #101
 * #125
 * https://github.com/haf/expecto/projects/1#card-2035713

### CODE REVIEW

**Comment by haf** [comment]
Rebuilding. I'm not sure why it hangs sometimes.

**Comment by adamchester** [comment]
Yeah Travis OSX has been struggling to download mono recently.

**Comment by haf** [comment]
Nuget merging done?

**Comment by adamchester** [comment]
Yep, it's done.

**Comment by haf** [comment]
Can we remove the OS X build on travis to make the build green?

**Comment by adamchester** [comment]
I think it's a temporary issue, but let me just try restarting that one failing job first...

**Comment by haf** [comment]
I've tried restarting it many times.

**Comment by adamchester** [comment]
Yep, I just tried again a few times and no luck. It fails to download mono.

Here are some issues and PRs I have found that appear related:
 * https://github.com/travis-ci/travis-ci/issues/7502
 * https://github.com/travis-ci/travis-ci/issues/7615
 * https://github.com/travis-ci/travis-build/pull/1021

From https://github.com/travis-ci/travis-ci/issues/7615#issuecomment-294211493
> Yeah the underlying issue seems to be with OSX + curl + Azure CDN.

**Comment by haf** [comment]
Let's add `os: osx` to https://github.com/haf/expecto/blob/b5be96c9fe69656ba8b4372e4bcd7e200c0870dd/.travis.yml#L32 under `allowed_failures`

**Comment by haf** [comment]
Excellent, I'll release the nuget in beta later today!

**Pull request merged**
