### PR TITLE
Report duplicated test names via printer

### LINKED ISSUE #336: Report duplicate names via printer
Could it be better for tooling if the error about duplicate names was reported via relevant printer instead of being written to the output? `exn` and `info` printers seem to suite well enough.

Although it would probably be a better design, the tooling would have to still support current approach as some existing projects may not get an updated Expecto package anytime soon. Due to this I'm not sure if it'd be a better overall situation for the tools but just wanted to share the thoughts.

- [Printers](https://github.com/haf/expecto/blob/master/Expecto/Expecto.fs#L643)
- [Location of printing](https://github.com/haf/expecto/blob/master/Expecto/Expecto.fs#L1952-L1956)

### PR DESCRIPTION
**Pull request by auduchinok**
Fixes #336.

### CODE REVIEW

**Comment by haf** [comment]
Have you validated this on a terminal, so that it doesn't mess up e.g. the console/ANSI escape codes?

**Comment by auduchinok** [comment]
Nope, only run the test suite via `fake`.
Isn't it something that should be covered by printers (already)?

**Comment by haf** [comment]
@auduchinok It is, but I never got around to proving that property in my head, because there's a certain amount of global state when printing to the console singleton. In all likelyhood, it's enough for you to run expecto with itself through its test suite on your terminal and see that it works.

**Comment by haf** [comment]
@auduchinok thank you for your contribution!

**Pull request merged**
