### PR TITLE
Restore errors

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
@AnthonyLloyd I change paket to allow nuget exe to do further downloads, but still it's not working on that environment. Can you try to use the https://github.com/SAFE-Stack/SAFE-BookStore/blob/master/appveyor.yml

**Comment by AnthonyLloyd** [comment]
Thanks for your efforts. What do you want me to do? Copy part of the appveyor.yml config?

**Comment by forki** [comment]
Yes. Everything is working locally for me. And bookstore is using expecto.
So I assume it should work on their appveyor settings

Am 12.01.2018 15:58 schrieb "Anthony Lloyd" <notifications@github.com>:

**Comment by AnthonyLloyd** [comment]
I tried the appveyor.yml setting without success. I also tried changing the dep file to take out BenchmarkDotNet and do Expecto.BenchmarkDotNet separately. I then deleted paket.lock and regenerated. I've tried updating dotnet core in travis.yml also.

I'm getting different dependency errors now:
https://travis-ci.org/haf/expecto/jobs/329256717

Its like the paket.lock generated isn't valid for travis & appveyor. Appveyor is a bit behind on its dotnet core SDK versions but travis is up to date.

**Comment by forki** [comment]
can you please apply my changes from the build.fsx here? they force install of matching dotnet sdk/cli

**Comment by AnthonyLloyd** [comment]
Sure thanks, will give it a go later today.

**Comment by forki** [comment]
@AnthonyLloyd I added a workaround to Paket and cleanup this PR. Please review

**Comment by forki** [comment]
this is green

**Comment by AnthonyLloyd** [comment]
:) Cool many thanks for all this.

I have one last question (it seems you are my new mentor!). I've been using `dotnet pack` when the references were in the project files. If I move to `paket pack` is there an easy way to not have to manually create the template files? I could write a template template and I guess all the dependencies will be resolved without having to put them in the files?

**Comment by forki** [comment]
what's the motivation to move?

**Comment by AnthonyLloyd** [comment]
I'm assuming that now the references are not in the project `dotnet pack` won't be able to include them properly. Does `paket` step in?

**Comment by forki** [comment]
yes. paket adds them automatically

**Comment by AnthonyLloyd** [comment]
Great, many thanks.

**Pull request merged**
