### PR TITLE
Added Expecto.Hopac

### LINKED ISSUE #226: Expecto.Hopac
I've extracted out some helpers for handling hopac jobs with expecto from some of our production code into this repo: 
https://github.com/TheAngryByrd/Expecto.Hopac/blob/master/src/Expecto.Hopac/Expecto.Hopac.fs

However since Expecto has the name reserved on nuget  (for good reason) I can't publish it.  Would you consider accepting a PR with a separate project that adds these helpers? 

Thanks!

### PR DESCRIPTION
**Pull request by TheAngryByrd**
This will add test wrappers for [Hopac](https://github.com/Hopac/Hopac) jobs 

closes #226

### CODE REVIEW

**Comment by haf** [comment]
Could you please not commit newline changes? 

https://github.com/haf/expecto/pull/231/files?w=1#diff-2bfb11ab4230093400363f8d70eab088

Should be +4 lines changed (link is with whitespace insensitive diff)

**Comment by TheAngryByrd** [comment]
Ugh sorry, gotta find the vscode plugin to punish.

**Comment by TheAngryByrd** [comment]
Ughhhhh, its 2018 why do we still have to deal with this crap

**Comment by haf** [comment]
LGTM from my side 👍

**Comment by AnthonyLloyd** [comment]
@TheAngryByrd the build has sometimes has the following error. Could this be coming from the hopac tasks?

Would also be good to get rid of the server GC warning. I tried to switch it to server GC but then it started causing some errors in my deadlock tests (memory I think) and didn't even stop the warning for net461.

```
Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.Win32Native.SetEvent(SafeWaitHandle handle)
   at System.Threading.EventWaitHandle.Set()
   at <StartupCode$FSharp-Core>.$Control.action@4236-16[TMsg](Mailbox`1 x, TMsg msg, Unit unitVar0)
   at Microsoft.FSharp.Control.Mailbox`1.Post(TMsg msg)
   at Expecto.Async.loop@261-6.Invoke(Unit unitVar) in /home/travis/build/haf/expecto/Expecto/Expecto.fs:line 270
   at Microsoft.FSharp.Control.AsyncBuilderImpl.econt@547.Invoke(ExceptionDispatchInfo exn)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@958-1.Invoke(ExceptionDispatchInfo edi)
   at <StartupCode$FSharp-Core>.$Control.loop@124-50(Trampoline this, FSharpFunc`2 action)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction)
   at <StartupCode$FSharp-Core>.$Control.-ctor@200-1.Invoke(Object o)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Running build failed.
Error:
System.Exception: dotnet command failed on Expecto.Tests/bin/Release/netcoreapp2.0/Expecto.Tests.dll --summary
  at Fake.DotNetCli+RunCommand@78-3.Invoke (System.String message) [0x00000] in <5a38ececccf1c534a7450383ecec385a>:0 
  at Microsoft.FSharp.Core.PrintfImpl+StringPrintfEnv`1[TResult].Finalize () [0x00012] in <5893d081904cf4daa745038381d09358>:0 
  at Microsoft.FSharp.Core.PrintfImpl+Final1@224[TState,TResidue,TResult,A].Invoke (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] env, A a) [0x00038] in <5893d081904cf4daa745038381d09358>:0 
  at Microsoft.FSharp.Core.OptimizedClosures+Invoke@3253[T2,TResult,T1].Invoke (T2 u) [0x00001] in <5893d081904cf4daa745038381d09358>:0 
  at Fake.DotNetCli.RunCommand (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] setCommandParams, System.String args) [0x00054] in <5a38ececccf1c534a7450383ecec385a>:0 
  at FSI_0005.Build+runTest@76.Invoke (System.String project) [0x0003b] in <7aaf114632de42d69fb549d4a4e06429>:0 
  at FSI_0005.Build+clo@74-8.Invoke (Microsoft.FSharp.Core.Unit _arg3) [0x0000a] in <7aaf114632de42d69fb549d4a4e06429>:0 
  at Fake.TargetHelper+targetFromTemplate@209-1[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) [0x00000] in <5a38ececccf1c534a7450383ecec385a>:0 
  at Fake.TargetHelper.runSingleTarget (Fake.TargetHelper+TargetTemplate`1[a] target) [0x00049] in <5a38ececccf1c534a7450383ecec385a>:0 
```

**Pull request merged**
