### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by sergey-tihon**
Fix for #72

@haf what also should I do?

>Albacore picks out the path from the fsproj file on publish, so just add an Icon element with the url to the properties and it'll be used.

Does it mean that image will be compiled as resource into Expecto dll?

### CODE REVIEW

**Comment by haf** [comment]
No, it's just an XML-element.

Could you please add the vector version?

**Comment by sergey-tihon** [comment]
I can do something like
```xml
 <PropertyGroup>
    <ApplicationIcon>https://github.com/haf/expecto/raw/master/docs/expecto-logo-small.png</ApplicationIcon>
  </PropertyGroup>
```
but i am not sure that it is correct

**Comment by haf** [comment]
Yes, but name it like the [nuspec](https://docs.microsoft.com/en-us/nuget/schema/nuspec) – `<IconUrl>...</IconUrl>`

Do you have the file as an `.ai`, otherwise I could vectorise it after merging. Thank you for creating a logo for the project!

**Comment by haf** [comment]
Docs [here](https://github.com/Albacore/albacore/wiki/nugets_pack)

**Comment by sergey-tihon** [comment]
@haf done, please update proj file by yourself

**Comment by haf** [comment]
Super, thank you!

**Pull request merged**
