### PR TITLE
remove reader writer locks

### PR DESCRIPTION
**Pull request by AnthonyLloyd**
Still failing! I've removed the reader writer locking and reduced the sleep. Hoping its only the number of workers and a small sleep needed.

### CODE REVIEW

**Comment by haf** [comment]
Soon you've tried everything! ;)

**Comment by AnthonyLloyd** [comment]
:) I've got it working now. It does need to be sequenced though as other tests are competing. Amazing its so hard to force a deadlock consistently.

Will do one more them squeeze them down.

**Comment by AnthonyLloyd** [comment]
@haf All done. Passed 12 travis build jobs and 3 more if these ok.

**Comment by haf** [comment]
Thank you @AnthonyLloyd!

**Pull request merged**
