### PR TITLE
add to performance and testSequenced docs

### PR DESCRIPTION
**Pull request by AnthonyLloyd**
@haf

### CODE REVIEW

**Comment by haf** [comment]
Thank you @AnthonyLloyd !

**Comment by AnthonyLloyd** [comment]
Just noticed a small typo. "Staring sequenced tests..." should be "Starting sequenced tests". In code and the doc png. Not major.

**Comment by haf** [comment]
Fixed

**Comment by AnthonyLloyd** [comment]
Thanks

**Pull request merged**
