### PR TITLE
Update BenchmarkDotNet to 0.14.0

### PR DESCRIPTION
**Pull request by Numpsy**
refs #495 

Updates BenchmarkDotNet  to the latest 0.14.0 release, and extends the Expecto code to implement the new members of ```IConfig``` - no changes other than that.

The changes to the properties here probably make this count as a breaking API change, but if  #501 is already a breaking change then perhaps that's an opportunity to do both at once?

(Note: I won't change the release notes etc here yet, as it'd probably just clash with #501)

### CODE REVIEW

**Comment by farlee2121** [comment]
Just merged #501, but I'll probably release it as a preview version first, since it's a breaking change 

This PR makes sense to me conceptually, but I'll admit that I don't really know much about Expecto.BenchmarkDotNet.

I scanned the [BenchmarkDotNet 14.0 release notes](https://benchmarkdotnet.org/changelog/v0.14.0.html) and our code. I didn't see any red flags. Is there anything else you were wanting to investigate before making this a full PR?

**Comment by Numpsy** [comment]
> Is there anything else you were wanting to investigate before making this a full PR?

I'll have a look at adding a release note entry later, then activate it.

**Comment by Numpsy** [comment]
> I don't really know much about Expecto.BenchmarkDotNet.

I want to try adding some new benchmarks to an existing Expecto test project, but I'm using ```UseArtifactsOutput``` in the build and BenchmarkDotNet 0.13 doesn't work with that - It's hopefully pretty straight forward, but I'll give it some more tests with a test or prerelease build

**Comment by Numpsy** [comment]
Does this need an entry in ```Migration notes``` as well as the release note? (anyone who is creating their own instances of ```BenchmarkConfig``` instead of using the default would have to populate the two new members)

**Comment by farlee2121** [comment]
Hmm. The changes seem pretty self explanatory. It's not nearly as disruptive as the fscheck 2 to 3 migration. The compiler warnings will likely tell people what they need to know.

**Comment by farlee2121** [comment]
This should be out with 11.0.0-alpha2

**Pull request merged**
