### PR TITLE
Add throwsAsync, throwsAsyncT, and throwsAsyncC

### PR DESCRIPTION
**Pull request by jwosty**
Async versions of the `throws` functions.

### CODE REVIEW

**Comment by jwosty** [comment]
@haf does this look good to you?

**Comment by haf** [comment]
I had a look and it’s looking good to me!

**Comment by jwosty** [comment]
Awesome, its' ready for review if you like these changes.

**Comment by farlee2121** [comment]
Sorry this slipped through the cracks. It's just been release with 10.2.0

**Comment by haf** [comment]
Awesome

**Pull request merged**
