### PR TITLE
use dotnet pack and nuspec instead of nuget client

### PR DESCRIPTION
**Pull request by enricosada**
To workaround nuget.commandline 3.5 who doesnt support prerelease deps as warning (instead of error)

fix https://github.com/haf/expecto/issues/165

In practice:

i didnt find a prerelease of nuget.commandline 4.0, so i used dotnet sdk, because anyway is required for final package.

`dotnet pack` = `dotnet msbuild /t:Pack` accept a nuspec file as property, instead of generate it from the msbuild project file itself (the common scenario for fsproj/csproj)

I added a project file `tools/nuget-workaround/nugetclient.proj` to be able to just run `Pack` target. like for `dotnet new` templates.

as a note, nuspec is just a temporary file now with new sdk. all props (minus owner) can be set as normal msbuild props and package generated with `Pack` target

TODO

- [x] win
- [x] osx/unix add bash script, alike of `tools/nuget-workaround/nugetclient.bat` to just invoke `dotnet msbuld` with passed arguments

### CODE REVIEW

**Comment by enricosada** [comment]
finally i have a working env for that mono version.

so atm doesnt work, my bad:

```
mono /home/enrico/expecto/tools/nuget-workaround/nugetclient Pack -OutputDirectory /home/enrico/expecto/build/pkg /home/
enrico/expecto/Expecto.BenchmarkDotNet/Expecto.BenchmarkDotNet.nuspec
Cannot open assembly '/home/enrico/expecto/tools/nuget-workaround/nugetclient': File does not contain a valid CIL image.
#<Albacore::CommandFailedError: Command failed with status (2):
```

because runt he command with `mono`. I'll fix that

**Comment by enricosada** [comment]
So my only problem atm is to say to `nugets_pack` to execute the command with `clr_command: false`

**Comment by haf** [comment]
https://github.com/Albacore/albacore/wiki/nugets_pack

**Comment by enricosada** [comment]
Ok @haf fixed also travis, ready to be merged

**Comment by haf** [comment]
Thank you for your hard work creating this PR. I really appreciate it!

**Comment by enricosada** [comment]
@haf np, was fun to remember how to monkey patch, and `albacore` codebase is really nice to work with (we use that at work for some proj).

**Pull request merged**
